Pages/Join.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Data.SqlClient;
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings;
using MovieNinja.Models;

namespace MovieNinja.Pages
{
    public class JoinModel : PageModel
    {
        public void OnGet() 
        {
            
        } // OnGet()

        public void OnPostSignup(string username, string password, string email) 
        {
            Program.dataNinja.Signup(username, password, email);
        } // OnPostSignup()

        public void OnPostLogin(string username, string password) 
        {
            Program.dataNinja.Login(username, password);
            Response.Redirect("./Index");
        } // OnPostLogin()

        public void OnPostLogout() 
        {
            Program.dataNinja.Logout();
            Response.Redirect("./Index");
        } // OnPostLogout()
    } // class
} // namespace

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Encode+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <title>@ViewData["Title"] - MovieNinja</title>
</head>
<body>
    <header>
    @{
        if(Program.userID == 0){
            <form id="loginForm" asp-page-handler="Login">
                <input type="text" name="username" placeholder="username">
                <input type="password" name="password" placeholder="password">
                <input type="submit" value="login">
            </form>
        }
        else{
            <form id="logoutForm" asp-page-handler="Logout">
                <a href="./Watchlist" title="Your watch list">watch list</a>
                <input type="submit" value="logout">
            </form>
        }
    }
    </header>

    <nav>
        <a href="./Index" title="home">home</a>
        <a href="./About" title="about">about</a>
        <a href="./Contact" title="contact">contact</a>
        <a href="./Join" title="join">join</a>
    </nav>

    <main>
        @RenderBody()
    </main>

    <footer>
    </footer>

    <script src="~/js/site.js"></script>
</body>
</html>