Models/Actor.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Security.Cryptography;
using System.Text;

namespace MovieNinja.Models
{
    public class Actor
    {
        public string birthday { get; set; }
        public string known_for_department { get; set; }
        public object deathday { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public List<string> also_known_as { get; set; }
        public int gender { get; set; }
        public string biography { get; set; }
        public double popularity { get; set; }
        public string place_of_birth { get; set; }
        public string profile_path { get; set; }
        public bool adult { get; set; }
        public string imdb_id { get; set; }
        public object homepage { get; set; }
    }
}

Pages/Actor.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Data.SqlClient;
using MovieNinja.Models;

namespace MovieNinja.Pages
{
    public class ActorModel : PageModel
    {
        public string biography;
        public string actorName;
        public string birthday;
        public int age;
        public string placeOfBirth;
        public string knownFor;
        public string homepage;
        public List<string> imageUrls = new List<string>();
        public List<string> movieImages = new List<string>();

        public async Task OnGet(string id)
        {
            await Program.fetch.GetActorDetails(id);
            await Program.fetch.GetActorImages(id);

            for(int i = 0; i < Program.profileSet.profiles.Count; i++)
            {
                imageUrls.Add(Program.profileSet.profiles[i].file_path);
            }

            await Program.fetch.GetRelatedMovies(id);

            for(int i = 0; i < Program.relatedSet.results.Count; i++)
            {
                movieImages.Add(Program.relatedSet.results[i].poster_path);
            }

            biography = Program.actor.biography;
            actorName = Program.actor.name;
            birthday = Program.actor.birthday;
            placeOfBirth = Program.actor.place_of_birth;
            knownFor = Program.actor.known_for_department;
            if(Program.actor.homepage != null)
                homepage = Program.actor.homepage.ToString();
        }
    }
}

Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using MovieNinja.Models;

namespace MovieNinja.Pages
{
    public class DetailsModel : PageModel
    {
        // Cast Details
        public List<string> castPics = new List<string>();
        public List<string> castNames = new List<string>();
        public List<int> actorIDs = new List<int>();

        // Movie details
        public string movieOverview;
        public int movieRuntime;
        public string movieTagline;
        public long movieRevenue;
        public string movieReleaseDate;
        public string moviePoster;
        public string movieTitle;
        public string movieYearAndRuntime;

        public async Task OnGet(string id)
        {
            Program.dataNinja.movieID = id;
            Program.dataNinja.poster_path = Program.movie.poster_path;
            Program.dataNinja.overview = Program.movie.overview;
            await Program.fetch.GetDetails(id);

            movieOverview = Program.movie.overview;
            movieRuntime = Program.movie.runtime;
            movieTagline = Program.movie.tagline;
            movieRevenue = Program.movie.revenue;
            movieReleaseDate = Program.movie.release_date;
            moviePoster = Program.movie.poster_path;
            movieTitle = Program.movie.title;
            movieYearAndRuntime = "released " + movieReleaseDate.Substring(0, 4) + " " + movieRuntime + "mins";

            for(int i = 0; i < Program.creditSet.cast.Count; i++)
            {
                castPics.Add(Program.creditSet.cast[i].profile_path);
                actorIDs.Add(Program.creditSet.cast[i].id);
                castNames.Add(Program.creditSet.cast[i].name);
            }
        }

        public void OnPostGetActor(string actorID) {
            Response.Redirect("./Actor?id=" + actorID);
        }

        public void OnPostAddToWatch(string movieID, string poster_path, string overview, string userID) {
            Program.dataNinja.AddToWatch(movieID, poster_path, overview, userID);
            Response.Redirect("./Details?id=" + Program.dataNinja.movieID);
        }

        public void OnPostLogin(string username, string password) 
        {
            Program.dataNinja.Login(username, password);
            Response.Redirect("./Details?id=" + Program.dataNinja.movieID);
        }
        public void OnPostLogout() 
        {
            Program.dataNinja.Logout();
            Response.Redirect("./Index");
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Data.SqlClient;
using MovieNinja.Models;

namespace MovieNinja.Pages
{
    public class IndexModel : PageModel
    {
        public List<string> posterURLS = new List<string>();
        public List<string> overviews = new List<string>();
        public List<string> movieIDs = new List<string>();

        public async Task OnGet()
        {
            await Program.fetch.GetTrends();
            foreach(Trend trend in Program.trendSet.results) {
                posterURLS.Add(trend.poster_path);
                overviews.Add(trend.overview);
                movieIDs.Add(trend.id.ToString());
            }
        } // OnGet()

        public async Task OnPostSearch(string search) {
            await Program.fetch.Search(search);
            foreach(Poster poster in Program.posterSet.results) {
                posterURLS.Add(poster.poster_path);
                overviews.Add(poster.overview);
                movieIDs.Add(poster.id.ToString());
            }
        }

        public void OnPostDetails(string movieID) {
            Response.Redirect("./Details?id=" + movieID);
        }

        public void OnPostLogin(string username, string password) 
        {
            Program.dataNinja.Login(username, password);
            Response.Redirect("./Index");
        }
        public void OnPostLogout() 
        {
            Program.dataNinja.Logout();
            Response.Redirect("./Index");
        }
    }
}

Pages/Join.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Data.SqlClient;
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings;
using MovieNinja.Models;

namespace MovieNinja.Pages
{
    public class JoinModel : PageModel
    {
        public void OnGet() 
        {
            
        } // OnGet()

        public void OnPostSignup(string username, string password, string email) 
        {
            Program.dataNinja.Signup(username, password, email);
        } // OnPostSignup()

        public void OnPostLogin(string username, string password) 
        {
            Program.dataNinja.Login(username, password);
            Response.Redirect("./Index");
        } // OnPostLogin()

        public void OnPostLogout() 
        {
            Program.dataNinja.Logout();
            Response.Redirect("./Index");
        } // OnPostLogout()
    } // class
} // namespace

Pages/Actor.cshtml
@page
@model ActorModel
@{
    ViewData["Title"] = "Movie Details";
}

<div id="actorDetails">
    <h1>@Model.actorName</h1>
    <h3>Born on @Model.birthday</h3>
    <h3>@Model.placeOfBirth</h3>
    <h3>Best known for: @Model.knownFor</h3>
    @if (Model.homepage != null)
    {
        <h3>@Model.homepage</h3>
    }
    <p class="bio">@Model.biography</p>
</div>

<div >
    @for (int i = 0; i < Model.imageUrls.Count; i++)
    {
        <img class="actorImages" src="https://image.tmdb.org/t/p/w500/@Model.imageUrls[i]" alt="pic" />
    }
</div>

Pages/Details.cshtml
@page
@model DetailsModel
@{
    ViewData["Title"] = "Movie Details";
    int MAX_CAST;
    if(Model.actorIDs.Count >= 10) {
        MAX_CAST = 10;
    }
    else {
        MAX_CAST = Model.actorIDs.Count;
    }
    string moviePoster = "https://image.tmdb.org/t/p/w1920_and_h800_multi_faces" + Program.movie.backdrop_path;
}

<form id="searchForm" method="POST" asp-page-handler="Search">
    <input id="searchBox" type="text" name="search" placeholder="enter your search here...">
</form>

<div id="movieDetails" style="background: radial-gradient(ellipse closest-side, 
        rgba(15, 14, 22, 0.75), #100e17), url(@moviePoster); background-size: cover;">

        <div id="movieDetailsLeft">
            <img class="movieDetailsPoster" src="https://image.tmdb.org/t/p/w500/@Model.moviePoster" alt="blah">
            <h2>@Model.movieYearAndRuntime</h2>
            @{
                if(Program.userID != 0) {
                    <form id="watchForm" asp-page-handler="AddToWatch">
                        <input type="hidden" name="movieID" value="@Program.dataNinja.movieID">
                        <input type="hidden" name="poster_path" value="@Program.dataNinja.poster_path">
                        <input type="hidden" name="overview" value="@Program.dataNinja.overview">
                        <input type="hidden" name="userID" value="@Program.userID">
                        <input type="submit" value="Add to watch">
                    </form>
                }
            }
        </div>
        <div id="movieDetailsRight">
            <h1>@Model.movieTitle</h1>
            <h3>@Model.movieTagline</h3>
            <p>@Model.movieOverview</p>
            <form method="POST" asp-page-handler="GetActor">
                @for(int i = 0; i < MAX_CAST; i++) {
                    string path = "https://image.tmdb.org/t/p/w500" + Model.castPics[i];
                    <div class="castThumbs" style="background: url(@path); background-size: 100%; background-position: center;" title="@Model.castNames[i]">
                        <input type="submit" class="thumbButton" name="actorID" value="@Model.actorIDs[i]" />
                    </div>
                }
            </form>
        </div>
</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<form id="searchForm" method="POST" asp-page-handler="Search">
    <input id="searchBox" type="text" name="search" placeholder="enter your search here...">
</form>

<div id="results">
    <form method="POST" asp-page-handler="Details">
        @for(int i = 0; i < Model.posterURLS.Count; i++) {
            string path = "https://image.tmdb.org/t/p/w500" + Model.posterURLS[i];
            <div class="thumb" style="background: url(@path); background-size: 100%;" title="@Model.overviews[i]">
                <input type="submit" class="thumbButton" name="movieID" value="@Model.movieIDs[i]" />
            </div>
        }
    </form>
</div>

Pages/Join.cshtml
@page
@model JoinModel
@{
    ViewData["Title"] = "Join our site today!";
}

<h1>Welcome to MovieNinja - please provide the following details to join:</h1>
<form id="signupForm" asp-page-handler="Signup">
    <input type="text" name="username" placeholder="type a username"><br>
    <input id="password1" type="password" name="password" placeholder="type a password"><br>
    <input id="password2" type="password" name="confirmPassword" placeholder="retype your password"><br>
    <input type="email" name="email" placeholder="type your email" onfocus="CheckPasswords();"><br>
    <input type="submit" value="Create Account">
</form>